#!/bin/sh
#
# Gradle start up script for POSIX generated by "Gradle init".
#
# (Simplified standard gradlew wrapper)

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")
APP_HOME=$(cd "$(dirname "$0")" && pwd)
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
JAVACMD="${JAVA_HOME}/bin/java"
if [ -z "$JAVA_HOME" ]; then
    JAVACMD="java"
fi

exec "$JAVACMD" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
